;; protocols - a set of 'how to behave' rules expressed in code

(defrecord Employee [first-name last-name department])
(def alice (->Employee "Alice" "Smith" "Engineering"))

(defprotocol Person
  (full-name [this])
  (greeting [this msg])
  (description [this]))
  ;; these three items are function. Functions generated by protocols are
  ;; polymorphic. Exactly what they do depends on the type of their first argument

(defrecord FictionalCharacter [name appears-in author]
  Person
  (full-name [this] (:name this))
  (greeting [this msg] (str msg " " (:name this)))
  (description [this]
    (str (:name this) " is a character in " (:appears-in this))))

(defrecord Employee [first-name last-name department]
  Person
  (full-name [this] (str first-name " " last-name))
  (greeting [this msg] (str msg " " (:first-name this)))
  (description [this]
    (str (:first-name this) " works in " (:department this))))

(def sofia (->Employee "Sofia" "Diego" "Finance"))
(def sam (->FictionalCharacter "Sam Weller" "The Pickwick Papers" "Dickens"))

;; now we can take advantage of our new polymorphic functions
(full-name sofia) ; "Sofia Diego"
(description sam) ; "Sam Weller is a character in The Pickwick Papers"

(greeting sofia "Hello!") ; "Hello! Sofia"
(greeting sam "Hello!") ; "Hello! Sam Weller"
(:author sam) ; "Dickens"

(defprotocol Marketable
  (make-slogan [this]))

(extend-protocol Marketable
  Employee
    (make-slogan [e] (str (:first-name e) " is the BEST employee!"))
  FictionalCharacter
    (make-slogan [fc] (str (:name fc) " is the GREATEST character!"))
  SuperComputer
    (make-slogan [sc] (str "This computer has " (:no-cpus sc) " CPUs!")))

(extend-protocol Marketable
  String
    (make-slogan [s] (str \" s \" " is a string! WOW!"))
  Boolean
    (make-slogan [b] (str b " is one of the two surviving Booleans!")))
